### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by shourgamer2** [shahriyardx/elogger#1]
What is this [repository](https://en.wikipedia.org/wiki/Repository) about like what type of  [logger](https://en.wikipedia.org/wiki/Logger) is this

**Comment by shahriyardx** [comment]
> What is this [repository](https://en.wikipedia.org/wiki/Repository) about like what type of  [logger](https://en.wikipedia.org/wiki/Logger) is this 

Express.js request logger. Like [Morgan](https://github.com/expressjs/morgan)

I made this for fun. Nothing serious.
